### ISSUE TITLE
Envoy `envoy.config.core.v3.HeaderValueOption` deprication

### ISSUE THREAD

**Issue by dermasmid** [knative-extensions/net-kourier#1117]
the proxy or logging this at high volume: 
`[source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.config.core.v3.HeaderValueOption Using deprecated option 'envoy.config.core.v3.HeaderValueOption.append' from file base.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.`

**Comment by nak3** [comment]
Thank you for reporting this. It will be fixed in the next release by https://github.com/knative-extensions/net-kourier/pull/1076
