### ISSUE TITLE
Do not use `FromContextOrDefaults()` in `translateIngress()`

### ISSUE THREAD

**Issue by nak3** [knative-extensions/net-kourier#968]
Currently, there are some places use `FromContextOrDefaults()` in `translateIngress()` function such as:

https://github.com/knative-sandbox/net-kourier/blob/649db2781d60dd6a5580806194b3df5378118ed9/pkg/generator/ingress_translator.go#L195
https://github.com/knative-sandbox/net-kourier/blob/649db2781d60dd6a5580806194b3df5378118ed9/pkg/generator/ingress_translator.go#L268

`FromContextOrDefaults()` returns the default value in `config-network` so controller temporarily creates a envoy configuration with unexpected configuration.
For example, `internal-encryption` is disabled by default so it creates envoy configuration without `internal-encryption` even if users enabled.

**Comment by ReToCode** [comment]
@nak3 do you know why we generate an initial envoy snapshot when the controller is constructed, instead just doing that on the first reconcile event? Is that so envoy can start?

**Comment by nak3** [comment]
Sorry, I am not familiar with it but I think it was implemented as there is an issue that controller sends an incomplete configuration to an already running gateway container as per the following PRs.
- https://github.com/knative-sandbox/net-kourier/pull/72
- https://github.com/knative-sandbox/net-kourier/pull/137
- https://github.com/knative-sandbox/net-kourier/pull/276
